### ISSUE TITLE
Chapter 06: unreadable image in dark mode

### ISSUE THREAD

**Issue by edilmedeiros** [sb1752/bitcoiner-intro-to-rust#16]
Took some time to understand what was going on with the svg. Turns out it renders crappy in the browser dark mode since there are black arrows over a transparent background.

<img width="698" alt="Screenshot 2024-05-19 at 22 14 16" src="https://github.com/sb1752/bitcoiner-intro-to-rust/assets/78322931/3b1ea2c1-d130-46f8-9cf9-d3ed68619691">

Reference: https://github.com/sb1752/bitcoiner-intro-to-rust/blob/f2ea4b04067053518b81b1347f3cdec57971b63f/06_pointers_and_slices.md?plain=1#L5

**Comment by sb1752** [comment]
Ah I see. Hm, I'll look into that.
